"""The migration chain must run against a database that has nothing in it.

Phase 01 verified this once and nothing kept verifying it. Phase 05's autogenerated
migration then picked up drops for LangGraph's checkpoint tables — invisible on a
developer's database where those tables happened to exist, and fatal on a fresh one:
the chain stopped at the first drop, so no new deployment could be provisioned.

The gap was in *when* it was checked, not in what. This runs the whole chain against a
throwaway database on every suite run, so the next migration that only works on one
particular machine fails here instead of on somebody's first install.
"""

import subprocess
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import psycopg
import pytest

from agentic_qa.infrastructure.agent.langgraph.checkpointer import LIBRARY_OWNED_TABLES
from tests.conftest import postgres_test_dsn


def psycopg_dsn(sqlalchemy_dsn: str) -> str:
    return sqlalchemy_dsn.replace("postgresql+asyncpg://", "postgresql://", 1)


def with_database(dsn: str, database: str) -> str:
    parts = urlsplit(dsn)
    return urlunsplit((parts.scheme, parts.netloc, f"/{database}", parts.query, parts.fragment))


def run_alembic(dsn: str, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["alembic", *args],
        capture_output=True,
        text=True,
        env={"PATH": "/usr/local/bin:/usr/bin:/bin:/opt/venv/bin", "POSTGRES_DSN": dsn},
        check=False,
    )


def test_the_whole_chain_applies_to_an_empty_database() -> None:
    """No fixture data, no library tables, nothing created by `create_all` first."""
    admin = with_database(psycopg_dsn(postgres_test_dsn()), "postgres")
    scratch = f"roveqa_migrate_{uuid4().hex[:12]}"

    try:
        with psycopg.connect(admin, autocommit=True) as connection:
            connection.execute(f'CREATE DATABASE "{scratch}"')
    except psycopg.OperationalError as error:
        pytest.skip(f"PostgreSQL not reachable: {error}")

    target = with_database(postgres_test_dsn(), scratch)
    try:
        upgrade = run_alembic(target, "upgrade", "head")
        assert upgrade.returncode == 0, upgrade.stderr[-3000:]

        # A chain that applies but then reports drift would leave every later
        # autogenerate proposing the same change again.
        check = run_alembic(target, "check")
        assert check.returncode == 0, check.stdout[-3000:] + check.stderr[-3000:]
    finally:
        with psycopg.connect(admin, autocommit=True) as connection:
            connection.execute(f'DROP DATABASE IF EXISTS "{scratch}" WITH (FORCE)')


def test_no_migration_touches_a_table_langgraph_owns() -> None:
    """LangGraph creates its own checkpoint tables through `setup()`.

    Dropping one destroys the resume state of every run in flight, and creating one
    means our schema and the library's can disagree after an upgrade. `alembic/env.py`
    excludes them from autogenerate; this catches a migration that names one anyway,
    which is exactly how the Phase 05 migration went wrong.
    """
    versions = Path(__file__).resolve().parents[2] / "alembic" / "versions"
    offenders = [
        f"{path.name}: {table}"
        for path in sorted(versions.glob("*.py"))
        for table in LIBRARY_OWNED_TABLES
        if f"'{table}'" in path.read_text(encoding="utf-8")
    ]

    assert offenders == [], f"migrations must not touch library-owned tables: {offenders}"
