"""phase 08 artifacts index

Revision ID: 00dfb54608c5
Revises: 0f1607fa06e7
Create Date: 2026-08-19 05:28:57.361664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dfb54608c5'
down_revision: Union[str, Sequence[str], None] = '0f1607fa06e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=200), nullable=False),
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('evidence_set_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=120), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('run_id', 'relative_path', name='uq_artifacts_run_path')
    )
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
