"""phase 08 model provenance

Revision ID: 27a82f4f015d
Revises: 00dfb54608c5
Create Date: 2026-08-19 06:49:34.735904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a82f4f015d'
down_revision: Union[str, Sequence[str], None] = '00dfb54608c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterion_results', sa.Column('model_invocation_id', sa.String(length=200), nullable=True))
    op.add_column('criterion_results', sa.Column('model_name', sa.String(length=200), nullable=True))
    op.add_column('criterion_results', sa.Column('prompt_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion_results', 'prompt_version')
    op.drop_column('criterion_results', 'model_name')
    op.drop_column('criterion_results', 'model_invocation_id')
    # ### end Alembic commands ###
