"""phase 07 test plans

Revision ID: 603bec952128
Revises: f9911e78285a
Create Date: 2026-08-19 00:55:58.976073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '603bec952128'
down_revision: Union[str, Sequence[str], None] = 'f9911e78285a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_plans',
    sa.Column('plan_id', sa.String(length=200), nullable=False),
    sa.Column('plan_version', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('source_story_id', sa.String(length=200), nullable=True),
    sa.Column('environment_id', sa.String(length=200), nullable=True),
    sa.Column('run_policy_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('memory_policy', sa.String(length=20), nullable=False),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_policy_id'], ['run_policies.policy_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_story_id'], ['user_stories.story_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('plan_id', 'plan_version')
    )
    op.create_index(op.f('ix_test_plans_project_id'), 'test_plans', ['project_id'], unique=False)
    op.add_column('runs', sa.Column('plan_id', sa.String(length=200), nullable=True))
    op.add_column('runs', sa.Column('plan_version', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_runs_test_plan_version', 'runs', 'test_plans', ['plan_id', 'plan_version'], ['plan_id', 'plan_version'], ondelete='RESTRICT')
    op.create_check_constraint('ck_runs_plan_identity_complete', 'runs', '(plan_id IS NULL) = (plan_version IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_runs_plan_identity_complete', 'runs', type_='check')
    op.drop_constraint('fk_runs_test_plan_version', 'runs', type_='foreignkey')
    op.drop_column('runs', 'plan_version')
    op.drop_column('runs', 'plan_id')
    op.drop_index(op.f('ix_test_plans_project_id'), table_name='test_plans')
    op.drop_table('test_plans')
    # ### end Alembic commands ###
