"""phase_09_memory_feedback_and_graph_sync

The other half of learning: what later runs discovered about the knowledge they used,
and whether that knowledge has reached the graph projection yet.

`memory_feedback` is unique per occurrence — candidate, run, episode, kind — because
reliability counts *independent* outcomes. Without that key, a retried activity votes
twice and one flaky observation can talk itself into being trusted.

`graph_sync_state` is separate from the candidate's status on purpose: the graph being
down says nothing about whether the knowledge is true, so an outage must not be able to
demote a promoted fact (ADR 0008).

Revision ID: 63d1345551d7
Revises: faaec9b601ae
Create Date: 2026-08-20 01:32:33.947053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d1345551d7'
down_revision: Union[str, Sequence[str], None] = 'faaec9b601ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_sync_state',
    sa.Column('candidate_id', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('graph_schema_version', sa.String(length=50), nullable=True),
    sa.Column('graph_node_id', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'synced', 'failed')", name='ck_graph_sync_state_known_state'),
    sa.ForeignKeyConstraint(['candidate_id'], ['knowledge_candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('ix_graph_sync_state_backlog', 'graph_sync_state', ['state', 'updated_at'], unique=False)
    op.create_table('memory_feedback',
    sa.Column('feedback_id', sa.String(length=200), nullable=False),
    sa.Column('candidate_id', sa.String(length=200), nullable=False),
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('episode_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('observed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['knowledge_candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('candidate_id', 'run_id', 'episode_id', 'kind', name='uq_memory_feedback_occurrence')
    )
    op.create_index('ix_memory_feedback_candidate', 'memory_feedback', ['candidate_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_feedback_candidate', table_name='memory_feedback')
    op.drop_table('memory_feedback')
    op.drop_index('ix_graph_sync_state_backlog', table_name='graph_sync_state')
    op.drop_table('graph_sync_state')
    # ### end Alembic commands ###
