"""phase 04 environments and run policies

Revision ID: 6c4d6570f65c
Revises: 492adc523ebb
Create Date: 2026-08-18 15:00:41.477903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c4d6570f65c'
down_revision: Union[str, Sequence[str], None] = '492adc523ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_policies',
    sa.Column('policy_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('allowed_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('upload_path_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destructive_actions', sa.Boolean(), nullable=False),
    sa.Column('allow_file_uploads', sa.Boolean(), nullable=False),
    sa.Column('allow_downloads', sa.Boolean(), nullable=False),
    sa.Column('synthetic_data_allowed', sa.Boolean(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_actions', sa.Integer(), nullable=False),
    sa.Column('max_model_calls', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_run_policies_project_id'), 'run_policies', ['project_id'], unique=False)
    op.create_table('environments',
    sa.Column('environment_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('default_run_policy_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_run_policy_id'], ['run_policies.policy_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('environment_id')
    )
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('default_run_policy_id', sa.String(length=200), nullable=True))
    op.add_column('runs', sa.Column('run_policy_id', sa.String(length=200), nullable=True))
    op.add_column('runs', sa.Column('environment_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'runs', 'run_policies', ['run_policy_id'], ['policy_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'runs', 'environments', ['environment_id'], ['environment_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'environment_id')
    op.drop_column('runs', 'run_policy_id')
    op.drop_column('projects', 'default_run_policy_id')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_run_policies_project_id'), table_name='run_policies')
    op.drop_table('run_policies')
    # ### end Alembic commands ###
