"""phase_12_explored_states

State maps from autonomous exploration, stored **per run** rather than merged into
one accumulating picture. A single table could say what an application offers; two
runs' maps say what changed, and only the second is worth waking somebody for.

`exploration_runs` is separate from `explored_states` because it answers a question
the states cannot: a map of twelve states that ran out of actions and a map of twelve
states that ran out of places to go look identical. Only the second can support the
claim that a state missing next time was removed — which is why `complete` is a
column and not an inference.

`affordance_keys` holds the normalised set the signature was computed from, so a
delta can say what a page gained or lost rather than only that it differs. The
original accessible names are not kept: they are page content, and a state map is
not an evidence store.

Revision ID: 8b3ac8f35fa4
Revises: cc429f184282
Create Date: 2026-08-20 09:17:33.183090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b3ac8f35fa4'
down_revision: Union[str, Sequence[str], None] = 'cc429f184282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_runs',
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('stop_reason', sa.String(length=30), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('actions_taken', sa.Integer(), nullable=False),
    sa.Column('states_discovered', sa.Integer(), nullable=False),
    sa.Column('max_depth_reached', sa.Integer(), nullable=False),
    sa.Column('frontier_remaining', sa.Integer(), nullable=False),
    sa.Column('declined', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stop_reason IN ('goal_reached', 'frontier_exhausted', 'max_actions', 'max_states', 'deadline')", name='ck_exploration_runs_stop_reason'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_exploration_runs_project_id'), 'exploration_runs', ['project_id'], unique=False)
    op.create_table('explored_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=2000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('affordance_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'signature', name='uq_explored_states_identity')
    )
    op.create_index('ix_explored_states_project_route', 'explored_states', ['project_id', 'route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_explored_states_project_route', table_name='explored_states')
    op.drop_table('explored_states')
    op.drop_index(op.f('ix_exploration_runs_project_id'), table_name='exploration_runs')
    op.drop_table('exploration_runs')
    # ### end Alembic commands ###
