"""phase 01 baseline projects stories criteria runs

Revision ID: a2fc1518b988
Revises: 
Create Date: 2026-08-18 13:13:47.782854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2fc1518b988'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'pausing', 'paused', 'recovering', 'cancelling', 'cancelled', 'failed', 'completed', name='run_status', native_enum=False, length=20), nullable=False),
    sa.Column('verdict', sa.Enum('passed', 'failed', 'blocked', 'inconclusive', 'cancelled', name='run_verdict', native_enum=False, length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'queued', 'running', 'pausing', 'paused', 'recovering', 'cancelling', 'cancelled', 'failed', 'completed')", name='ck_runs_status'),
    sa.CheckConstraint("verdict IS NULL OR status IN ('completed', 'failed', 'cancelled')", name='ck_runs_verdict_only_when_terminal'),
    sa.CheckConstraint("verdict IS NULL OR verdict IN ('passed', 'failed', 'blocked', 'inconclusive', 'cancelled')", name='ck_runs_verdict'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_table('user_stories',
    sa.Column('story_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forbidden_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_index(op.f('ix_user_stories_project_id'), 'user_stories', ['project_id'], unique=False)
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.String(length=200), nullable=False),
    sa.Column('criterion_id', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('verification_hint', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'criterion_id', name='uq_acceptance_criteria_story_criterion'),
    sa.UniqueConstraint('story_id', 'position', name='uq_acceptance_criteria_story_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acceptance_criteria')
    op.drop_index(op.f('ix_user_stories_project_id'), table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('projects')
    # ### end Alembic commands ###
