"""phase_11_failure_clusters

Deterministic failure triage, stored durably so "twenty runs hit this wall" is a
statement about a project's history rather than something recomputed and forgotten.

Three tables rather than one, because the split is the guarantee. `failure_clusters`
and `failure_cluster_members` are what was observed and how it was grouped;
`cluster_hypotheses` is what a large model guessed about it. No statement writes
both, so a hypothesis can never overwrite the evidence that justifies a cluster.

A member row is a pointer at `criterion_results`, not a copy: the observation and
the evidence refs already live there, and a second copy is free to drift.

The check constraints are the same rules the domain types enforce, restated where
the database can refuse them: a hypothesis row that claims not to be model-derived,
or one that reports a failure and a cause at the same time, is a contradiction no
reader could resolve.

Revision ID: cc429f184282
Revises: 63d1345551d7
Create Date: 2026-08-20 06:51:10.487071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc429f184282'
down_revision: Union[str, Sequence[str], None] = '63d1345551d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('cluster_id', sa.String(length=200), nullable=False),
    sa.Column('failure_kind', sa.String(length=20), nullable=False),
    sa.Column('criterion_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('http_status', sa.String(length=10), nullable=True),
    sa.Column('route', sa.String(length=2000), nullable=True),
    sa.Column('representative_run_id', sa.String(length=200), nullable=False),
    sa.Column('blocked_by', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'blocked_downstream') OR (blocked_by IS NULL)", name='ck_failure_clusters_blocked_by'),
    sa.CheckConstraint("status IN ('independent', 'blocked_downstream')", name='ck_failure_clusters_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cluster_id', name='uq_failure_clusters_identity')
    )
    op.create_index('ix_failure_clusters_project_seen', 'failure_clusters', ['project_id', sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_table('cluster_hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_pk', sa.Integer(), nullable=False),
    sa.Column('analyzed_run_id', sa.String(length=200), nullable=False),
    sa.Column('probable_cause', sa.Text(), nullable=False),
    sa.Column('recommended_check', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('model_derived', sa.Boolean(), nullable=False),
    sa.Column('failure', sa.Text(), nullable=True),
    sa.Column('model_invocation_id', sa.String(length=200), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(failure IS NULL) OR (probable_cause = '')", name='ck_cluster_hypotheses_failure_has_no_cause'),
    sa.CheckConstraint("confidence IN ('low', 'medium', 'high')", name='ck_cluster_hypotheses_confidence'),
    sa.CheckConstraint('model_derived', name='ck_cluster_hypotheses_model_derived'),
    sa.ForeignKeyConstraint(['analyzed_run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_pk'], ['failure_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_pk', 'analyzed_run_id', name='uq_cluster_hypotheses_pass')
    )
    op.create_table('failure_cluster_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_pk', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('criterion_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cluster_pk'], ['failure_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_pk', 'run_id', 'criterion_id', name='uq_failure_cluster_members_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_cluster_members')
    op.drop_table('cluster_hypotheses')
    op.drop_index('ix_failure_clusters_project_seen', table_name='failure_clusters')
    op.drop_table('failure_clusters')
    # ### end Alembic commands ###
