"""phase 05 recovery points

Autogenerate originally added drops for LangGraph's checkpoint tables here, because
`alembic/env.py` did not yet exclude library-owned tables when this was written. They
are removed rather than kept: dropping them destroys the resume state of any run in
flight, and on an empty database the drops fail outright, so the whole chain could not
be applied to a fresh deployment. LangGraph creates and owns those tables through its
own `setup()`.

Revision ID: f9911e78285a
Revises: 6c4d6570f65c
Create Date: 2026-08-18 15:53:39.732161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f9911e78285a'
down_revision: Union[str, Sequence[str], None] = '6c4d6570f65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_points',
    sa.Column('recovery_point_id', sa.String(length=200), nullable=False),
    sa.Column('run_id', sa.String(length=200), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('graph_checkpoint_id', sa.String(length=500), nullable=False),
    sa.Column('browser_url', sa.Text(), nullable=False),
    sa.Column('page_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('storage_state_ref', sa.String(length=200), nullable=True),
    sa.Column('last_verified_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recovery_point_id')
    )
    op.create_index(op.f('ix_recovery_points_run_id'), 'recovery_points', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_points_run_id'), table_name='recovery_points')
    op.drop_table('recovery_points')
    # ### end Alembic commands ###
