"""phase_09_knowledge_candidates

Durable knowledge (ADR 0008). FalkorDB/Graphiti holds a projection rebuilt from this
table, so this is the only place a learned fact actually exists.

The two check constraints are not belt-and-braces. `model_derived AND trusted` is the
one combination that turns a model's guess into something later runs act on as fact,
and a row with neither source is knowledge from nowhere: both are cheap for the
database to refuse and expensive to discover later.

Revision ID: faaec9b601ae
Revises: 27a82f4f015d
Create Date: 2026-08-19 07:30:14.625165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faaec9b601ae'
down_revision: Union[str, Sequence[str], None] = '27a82f4f015d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_candidates',
    sa.Column('candidate_id', sa.String(length=200), nullable=False),
    sa.Column('project_id', sa.String(length=200), nullable=False),
    sa.Column('environment_id', sa.String(length=200), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observed', sa.Boolean(), nullable=False),
    sa.Column('model_derived', sa.Boolean(), nullable=False),
    sa.Column('source_run_id', sa.String(length=200), nullable=False),
    sa.Column('source_episode_id', sa.String(length=200), nullable=True),
    sa.Column('evidence_set_id', sa.String(length=200), nullable=True),
    sa.Column('test_plan_version', sa.String(length=100), nullable=True),
    sa.Column('model_invocation_id', sa.String(length=200), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('page_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=500), nullable=True),
    sa.Column('policy_id', sa.String(length=200), nullable=True),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT (model_derived AND status = 'trusted')", name='ck_knowledge_candidates_model_derived_never_trusted'),
    sa.CheckConstraint('observed OR model_derived', name='ck_knowledge_candidates_has_a_source'),
    sa.CheckConstraint('reliability >= 0 AND reliability <= 1', name='ck_knowledge_candidates_reliability'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('project_id', 'environment_id', 'dedup_key', name='uq_knowledge_candidates_dedup')
    )
    # Retrieval order: scope, then what is actionable, then the ranking. Scope leads
    # because it is a hard filter — memory from another project is not weaker evidence,
    # it is evidence about something else.
    op.create_index(
        'ix_knowledge_candidates_retrieval',
        'knowledge_candidates',
        ['project_id', 'environment_id', 'status', sa.text('reliability DESC')],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_candidates_retrieval', table_name='knowledge_candidates')
    op.drop_table('knowledge_candidates')
    # ### end Alembic commands ###
